-- Вложения-файлы в сообщениях чата

ALTER TABLE crew_messages ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE crew_messages ADD COLUMN IF NOT EXISTS file_name VARCHAR(500);
ALTER TABLE crew_messages ADD COLUMN IF NOT EXISTS file_mime VARCHAR(120);
ALTER TABLE crew_messages ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE crew_messages ADD COLUMN IF NOT EXISTS depo_path TEXT;

ALTER TABLE crew_dm ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE crew_dm ADD COLUMN IF NOT EXISTS file_name VARCHAR(500);
ALTER TABLE crew_dm ADD COLUMN IF NOT EXISTS file_mime VARCHAR(120);
ALTER TABLE crew_dm ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE crew_dm ADD COLUMN IF NOT EXISTS depo_path TEXT;
